
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpolzfohirmqkmvubjzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwb2x6Zm9oaXJtcWttdnVianpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTE2NTYsImV4cCI6MjA2Mjg4NzY1Nn0.VFWscgB-afT3Vm8QLST-IsQsfDMuMZcYyKE0S8y5s_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
